- 단축키 ESC/Enter : 명령 모드/수정 모드
- RUN : Ctrl/Shift/Art + Enter
- 셀 지우기 : X
- 코드/마크업 : Y/M

파이썬 특징
- 빌드 없이 바로 실행하는 인터프리터, 스크립트

In [1]:
# // 몫만 정수로, ** 승수
1+3, 1*3, 2-1, 3/2, 3//3, 3**3

(4, 3, 1, 1.5, 1, 27)

In [2]:
# 논리연산자
# 여러줄 주석 '''''', """""" 번거로우므로 보통 홑따옴표를 사용
'''
&&& and
|| or
! not
'''
True or False

True

In [3]:
# 조건문, 보통 소괄호 없이 사용합니다.
if (5 > 3):
    print('5 > 3')
if 5 > 3:
    print('5 > 3')

5 > 3
5 > 3


In [4]:
# 반복문 기존: 3항 연산자 반복문
# for (int i=0; i<3; i++){}
for i in range(3): # 향상된 for문이라고 불리던 반복문
    print(i)

0
1
2


In [5]:
# for 지정된 횟수만큼 반복 while 조건을 만족할때까지 반복
import random
# 0~1 랜덤값을 생성하는데 0.1보다 작은 값을 얻겠다.

while (True):
    v = random.random()
    print(v)
    if v < 0.1:
        break

0.23413052473344498
0.2053920777703111
0.3268718443659957
0.31567639256684366
0.33499514526525953
0.25067083897473175
0.2901927984613467
0.4973325089667603
0.27730866415659206
0.5328244203887179
0.627570015690343
0.9621260528386817
0.9781295574312034
0.00414091237612757


In [6]:
# 함수
'''
기존
int add(int a, int b){
    return a+b;
}
'''
# 셀 하나에 함수를 정의하는 것이 깔끔하다.
def add(a, b):
    return a + b

In [7]:
add(3, 5), add(1.5, 6.7), add('abc', '123')

(8, 8.2, 'abc123')

In [8]:
# 클래스, 셀 하나에 정의하세요
class Lotto:
    def __init__(self, k): # 생성자
        nums = [] # 지역변수 (함수 실행 완료되면 사라집니다.)
        self.nums = [] # 클래스변수 (클래스가 제거되기 전까지 남습니다.)
        for i in range(k):
            nums.append(random.randint(1, 45))
        print(nums)

In [9]:
# 객체 생성
lotto1 = Lotto(3)
lotto2 = Lotto(5)

[21, 45, 26]
[31, 13, 42, 39, 1]


In [10]:
lotto1.nums # 클래스 변수를 .으로 접근해서 사용할 수 있습니다.

[]

데이터 타입,
- 딕셔너리 {키:값, 키:값...}       !엑셀의 컬럼 이름: 키, 컬럼의 값들:값
- 리스트 [값, 값, 값...] 수정가능  !언제든지 편리하게 데이터를 저장
- 튜플 (값, 값, 값) 수정불가능     !함수에서 값들을 여러개 리턴할때

In [16]:
d = {'age':30, 'city':'Seoul'}
l = [10, 'a', 'city', [1,2,3]]
t = (10, '1', 'city', [1,2,3])
d, l, t

({'age': 30, 'city': 'Seoul'},
 [10, 'a', 'city', [1, 2, 3]],
 (10, '1', 'city', [1, 2, 3]))

In [17]:
# 인덱스, 인덱싱
# 0을 인덱스라고 하고 반드시 정수여야 합니다.
# 인덱스로 값을 꺼내는 것을 인덱싱한다고 합니다.
# -1 뒤에서 첫번째 위치
# [시작위치 : 끝 위치 전까지], [생략:생략]
ㅣ[0], l[-1], ㅣ[1:3]

(10, [1, 2, 3], ['a', 'city'])

In [ ]:
# 요소들끼리 더하고 싶다 :element wise add
[1,2,3]+[3,4,5]

List, Dict, Set 연산용으로 사용이 불가능, 메모리 사용량이 크고 느립니다.

In [99]:
import numpy
import numpy as np # as 는 별칭(alias)

In [100]:
# 배열 만들기
# 함수 사용시 shift+Tab 로 설명을 봅니다
numpy.arange(1,10), numpy.arange(1,10,2)

TypeError: 'list' object is not callable

In [108]:
# 데이터를 numpy 배열로 변환하면 연산이 됩니다
np.array([1,2,3])+np.array([4,5,6])

TypeError: 'list' object is not callable

야후 파이낸스의 SP500 주식 데이터를 읽습니다.
csv 혹은 pandas 로 읽을 수 있습니다.

In [22]:
import pandas
import numpy as np # as 는 별칭(alias)

In [50]:
stock = pandas.read_csv('^GSPC.csv')
stock.shape

(20, 7)

In [51]:
arr = np.array(stock) #배열로 변환
arr.shape

(20, 7)

In [52]:
arr[0] # 첫번째 행

array(['2019-05-20', 2841.939941, 2853.860107, 2831.290039, 2840.22998,
       2840.22998, 3288870000], dtype=object)

In [53]:
arr[0] ==arr[0,:]

array([ True,  True,  True,  True,  True,  True,  True])

In [54]:
arr[0,0], arr[-1, -1]

('2019-05-20', 1579314342)

In [33]:
close = arr[:,4] # 도 가능하지만
close = arr[:, -3] #이 편합니다
close

array([2840.22998, 2864.360107, 2856.27002, 2822.23999, 2826.060059,
       2802.389893, 2783.02002, 2788.860107, 2752.060059, 2744.449951,
       2803.27002, 2826.149902, 2843.48999, 2873.340088, 2886.72998,
       2885.719971, 2879.840088, 2891.639893, 2886.97998, 2889.669922],
      dtype=object)

In [55]:
# b(below) 아래쪽에 셀 만들기
# open의 최대값, 최소값, 평균을 구해보자
# 내장함수 : import 없이 바로 사용 가능한 함수
max(o), min(o), np.max(o), np.min(o), np.mean(o), np.median(o), np.std(o)

TypeError: '<' not supported between instances of 'int' and 'str'

In [56]:
# Open->high->Low->close 4개의 컬럼만 뽑자
# [시작:끝]
v4 = arr[:, 1:5]
v4.shape

(20, 4)

축 : axis
2차원 데이터는 2개의 축이 있습니다. 행축, 열축

In [41]:
np.max(v4) # v4에서 최대값
np.max(v4, axis=0) # axis=0 => 행데이터에서 각각의 최대값

array([2903.27002, 2910.610107, 2887.300049, 2891.639893], dtype=object)

In [57]:
np.max(v4, axis=1) # axis=1 => 열데이터에서 각각의 최대값

array([2853.860107, 2868.8798829999996, 2865.469971, 2836.699951,
       2841.360107, 2840.51001, 2792.030029, 2799.0, 2768.97998,
       2763.070068, 2804.48999, 2827.280029, 2852.100098, 2884.969971,
       2904.77002, 2910.610107, 2888.570068, 2895.23999, 2894.449951,
       2897.27002], dtype=object)

In [83]:
# arg_max, arg_min 최대/최소값의 위치
np.max(o), np.argmax(o)

TypeError: 'list' object is not callable

주가가 가장 많이 상승한 날짜를 찾아보세요(정답: X번째 행입니다.)
(종가-시작)이 가장 큰 날입니다.

In [85]:
day = arr[:, 0]
close_v = arr[:, -3]
open_v = arr[:, 1]
gap = close_v-open_v
gap

array([-1.7099610000000212, 10.34008700000004, 0.20996100000002116,
       -14.459961000000021, -6.3498530000001665, -27.640135999999984,
       -7.229980000000069, 1.920165999999881, -14.0898430000002,
       -7.080077999999958, 40.6301269999999, 8.059814000000188,
       14.979980000000069, 20.469970999999532, 0.899902000000111,
       -17.550048999999944, -2.8898920000001453, 5.399902999999995,
       0.15991200000007666, -0.08007799999995768], dtype=object)

In [86]:
np.max(gap), np.argmax(gap), day[np.max(gap)]

TypeError: 'list' object is not callable

#### 데이터분석
- 가격 상승하는 날 거래량이 많아질까?
- 전날 가격이 상승하면 다음날 시작가격은 더 높은 가격에서 시작할까?
- 가격 변동이 크면 거래량도 많아질까?

#### 다음 단계: 예측
- 어제/오늘 현황 분석이 끝났는데 내일은 Open이 어떻게 될까
- 예측방법: 1.통계적예측(R), 2.머신러닝예측

In [102]:
# 가격이 상승한 날 거래량이 많아질까?
# >상승한 날의 거래량/ 하락한 날의 거래량

close_v = arr[:, -3]
open_v = arr[:, 1]
vol = arr[:, -1]
gap = close_v-open_v

In [104]:
# 상승한 날의 거래량 평균
np.mean(vol[gap >0]), np.mean(vol[gap<0])

(3286227000.0, 3397639434.2)

In [105]:
# 상승한 날의 거래량이 더 많냐?
np.mean(vol[gap >0]) > np.mean(vol[gap<0])

False

In [106]:
a= np.array([1,2,3,4])
even = a%2 ==0
even # 불린 마스크

array([False,  True, False,  True])

In [107]:
# 불린 마스크를 인덱스로 사용하면 True 값만 뽑힙니다
a[even]

TypeError: 'list' object is not callable

In [110]:
import numpy as np

In [112]:
a = np.array([1,2,3])

In [115]:
a, a.dtype

TypeError: 'list' object is not callable

In [119]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [121]:
np.zeros(shape=(2, 3, 4), dtype=np.int32)

TypeError: 'list' object is not callable

In [122]:
np.ones(shape=(3,2,4), dtype=np.int32)

TypeError: 'list' object is not callable

In [123]:
np.full((3,2,4),3.14)

TypeError: 'list' object is not callable

In [124]:
np.eye(4)

TypeError: 'list' object is not callable

In [125]:
np.arange(0,10,3)

TypeError: 'list' object is not callable